version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build_front_end: # this can be any name you choose
    working_directory: ~/dgsim/app
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout:
          path: ~/dgsim
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  build_and_test_backend:
    working_directory: ~/dgsim/server
    docker:
      - image: circleci/php:7/4-node-browsers
    steps:
      - checkout:
        path: ~/dgsim
      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: "Install Dependencies"
          command: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

workflows:
  my-workflow:
    jobs:
      - build_front_end
      - buld_and_test_backend
